# Multiple Linear Regression

## Importing libraries

In [12]:
%config IPcompleter.greedy = True
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Dataset

In [13]:
data=pd.read_csv("50_Startups.csv")
X=data.iloc[:,:-1].values
# print(X)
y=data.iloc[:,-1].values
#y

## Encoding Categorical Data

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[3])],remainder="passthrough")
X=np.array(ct.fit_transform(X))
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

## Splitting the Dataset

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)


In [16]:
print(X_train)

[[0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 0.0 22177.74 154806.14 28334.72]
 [0.0 1.0 0.0 67532.53 105751.03 304768.73]
 [1.0 0.0 0.0 44069.95 51283.14 197029.42]
 [1.0 0.0 0.0 38558.51 82982.09 174999.3]
 [0.0 1.0 0.0 75328.87 144135.98 134050.07]
 [1.0 0.0 0.0 0.0 135426.92 0.0]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 77044.01 99281.34 140574.81]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 1.0 0.0 61994.48 115641.28 91131.24]
 [1.0 0.0 0.0 46426.07 157693.92 210797.67]
 [0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 23640.93 96189.63 148001.11]
 [0.0 0.0 1.0 46014.

In [17]:
print(y_train)

[155752.6  134307.35  35673.41 149759.96  49490.75 129917.04 122776.86
 182901.99  65200.33 108733.99  89949.14  81005.76 105733.54  42559.73
  77798.83 125370.37 108552.04 191792.06 191050.39  99937.59  96712.8
 103282.38  71498.49  96479.51 141585.52  64926.08  97483.56 101004.64
 192261.83  97427.84  90708.19 126992.93 118474.03 166187.94  96778.92
 146121.95 107404.34 156991.12  81229.06  69758.98]


In [18]:
print(X_test)

[[0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 0.0 0.0 116983.8 45173.06]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]]


In [19]:
print(y_test)

[132602.65  78239.91 144259.4   14681.4  105008.31 110352.25 152211.77
 156122.51 111313.02 124266.9 ]


## Training the Multiple Linear Regression on Training Set

In [20]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## prediting the test set results

In [21]:
y_pred=regressor.predict(X_test)
print(y_pred)

[151928.35  77746.49 134797.27  51116.32 117562.6  117788.65 153488.05
 157540.21 121012.17 130826.82]


## Comparing the Predicted Value

In [22]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[151928.35 132602.65]
 [ 77746.49  78239.91]
 [134797.27 144259.4 ]
 [ 51116.32  14681.4 ]
 [117562.6  105008.31]
 [117788.65 110352.25]
 [153488.05 152211.77]
 [157540.21 156122.51]
 [121012.17 111313.02]
 [130826.82 124266.9 ]]


## Evaluating the Efficiency using R Squared

In [24]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8645681344931408